### ISSUE TITLE
프로젝트 초기 설정

### ISSUE THREAD

**Issue by KIMSEUNGGYU** [YAPP-Github/21st-Web-Team-2-FE#1]
## 💡 목적 
- 프로젝트 초기 셋팅을 잘해보자

## 📝 Todo
- [x]  issue / pr template 추가
- [x] Github Projects
- [x] formatting  추가
  - [x] prettier 추가
  - [x] eslint 추가
- [x]  emotions 설치
- [x]  recoil 설치
- [x] react-query 및 axios 설치
- [ ]  testing library 적용
    - [ ]  jest
    - [ ]  cypress
 - [ ]  storybook, chromatic 설정 @김현우
 - [ ] Github Label 추가하기 (논의 필요)
 - [x] Github Projects 
- [ ]  초기세팅 feature에서 작업 후 main에 넣기

## ‼️ 주의 사항
- 작업 브랜치 확인 필수! `feature/001-setting`
- 작업 및 push 할 때 `git fetch` 및 `npm install` 필수
- ESLint 모두 적용되는지 확인해주세요! (`pages/_app.tsx`) 확인
