### ISSUE TITLE
[feat] 분야별 표기 방식 지정

### ISSUE THREAD

**Issue by hwookim** [YAPP-Github/21st-Web-Team-2-FE#106]
## 💡 목적

- 디자인과 맞게 수정 
- 기타를 고려

## 📝 Todo

- [x] 기타를 고려해서 타입 string으로 변경
- [x] 기타를 고려한 리팩토링
- [x] 기존 developer... -> 개발, 디자인, 기획 으로 수정
