### ISSUE TITLE
[feat] 코드블럭 관리 방식 변경

### ISSUE THREAD

**Issue by hwookim** [YAPP-Github/21st-Web-Team-2-FE#107]
## 💡 목적

최소 높이 지정

## 📝 Todo

- [x] 최소 높이 지정
- [x] 상세페이지도 일괄적으로 최소 높이 지정
- [x] #83 함께 반영 -> hover 시 기존 레이아웃 뚫고 보여주도록
