### ISSUE TITLE
[feat] 토픽 상세 페이지에서 해당 토픽 시각화 나타내기

### ISSUE THREAD

**Issue by KIMSEUNGGYU** [YAPP-Github/21st-Web-Team-2-FE#111]
## 💡 목적
![image](https://user-images.githubusercontent.com/45627868/218300867-fc5fe959-9a9f-436a-8efb-ad9646a5889c.png)

## 📝 Todo
- [ ] 토픽 상세 조회시 api 와 함께 렌더링 되는 구조로 가는지 확인하기
- [ ] 토픽 상세 api 를 받고 해당 UI 로 나타내기
   - [ ] 논의 필요? 본인으로 인해 투표가 수정될시 해당 UI도 실시간으로 변경해야 하는지?
