### ISSUE TITLE
[refactor] react-query hook 관리 방식 통일

### ISSUE THREAD

**Issue by hwookim** [YAPP-Github/21st-Web-Team-2-FE#135]
## 💡 목적

약간 중구난방인 관리 방식 통일

## 📝 Todo

- [ ] 도메인별 폴더 묶기
- [ ] export default로 관리
- [ ] index.ts를 통해 접근할 수 있게 하기

## ‼️ 주의 사항

@KIMSEUNGGYU 
의견을 구합니다!

**Comment by KIMSEUNGGYU** [comment]
도메인별 폴더 묶기 좀 더 자세하게 이야기해줄 수 있을까요??

그 외 나머지는 좋은거 같아요!! 저희가 각 기능마다 query 를 만들어서 default 로 export 하는게 맞는거 같아요!

**Comment by hwookim** [comment]
@KIMSEUNGGYU 
도메인별 묶기는 `/api` 폴더에 각 파일 별로 묶은 것처럼 query hook도 한번은 묶어줄 필요가 있지 않나 싶어서 제안한 내용입니다.
topic 폴더에는 `useCeateTopic`, `useGetTopic`, `usePopularTopic` 등이 들어가도록요!

점점 훅이 많아질 수록 찾기가 힘들어질 것 같아서요 😅
