### ISSUE TITLE
[feat] 토픽 내용 공유시 meta 정보(Open Graph) 나오게 하기

### ISSUE THREAD

**Issue by KIMSEUNGGYU** [YAPP-Github/21st-Web-Team-2-FE#140]
## 💡 목적
![image](https://user-images.githubusercontent.com/45627868/219935249-8a8555b6-a7bc-4c49-a1bb-97d4df33a604.png)
- 현재 토픽 내용 공유시 이미지와 description 문구 없어, thumbs-up 로고와 description 확인할 수 있도록 하기

## 📝 Todo
- [x] kakao, facebook 등 메타 정보 등록하기 (이미지, description)
- [x] 홈페이지 공유했을때 적용
- [x] 토픽 공유했을때 적용
