### ISSUE TITLE
[chore] cypress, tsconfig, jest path alias 적용

### ISSUE THREAD

**Issue by KIMSEUNGGYU** [YAPP-Github/21st-Web-Team-2-FE#15]
## 💡 목적
- path alias 적용
  - `@src`, `@mocks` path alias 적용  
  - jest, cypress, tsconfig 적용

## 📝 Todo
- [x] jest path alias 적용
- [x] cypress path alias 적용
- [x] tsconfig path alias 적용
