### ISSUE TITLE
[feat] 상세 페이지 시각화 기능 구현

### ISSUE THREAD

**Issue by KIMSEUNGGYU** [YAPP-Github/21st-Web-Team-2-FE#155]
## 💡 목적
<img width="544" alt="스크린샷 2023-02-22 오후 6 44 27" src="https://user-images.githubusercontent.com/45627868/220583053-109cd4b0-13f9-4e4c-b677-7732f628adaa.png">

## 📝 Todo
- [ ] 각 직군별 참여자수(투표율) 보이기 (상세 페이지 접근 시 항상 보임)
- [ ] 로그인한 유저가 투표를 할 시 해당 직군에 맞게 투표자 수(투표율) 보이기  (투표시에 UI 보여줌)
- [ ] msw 기반 구현
- [ ] 서버 기반 구현
