### ISSUE TITLE
[feat] Text Topic Card 컴포넌트 구현

### ISSUE THREAD

**Issue by hwookim** [YAPP-Github/21st-Web-Team-2-FE#29]
## 💡 목적

<img width="825" alt="스크린샷 2023-01-04 11 49 53" src="https://user-images.githubusercontent.com/45786387/210475344-ac99a6e9-2942-4aea-82e3-7977d8218a45.png">

## 📝 Todo

- [x] 텍스트 기반의 토픽 카드 컴포넌트 구현
  - [x] 뱃지 여부
  - [x] feed, detail 속성
  - [x] 항목 수에 따른 배치

## ‼️ 주의 사항

- [x] 추후 이미지, 코드 등이 추가될 것을 고려하고 코드 작성하기
