### ISSUE TITLE
[feat] 댓글 리스트 UI 구현

### ISSUE THREAD

**Issue by KIMSEUNGGYU** [YAPP-Github/21st-Web-Team-2-FE#31]
## 💡 목적
![image](https://user-images.githubusercontent.com/45627868/210687654-70f44137-3b97-472d-bc9b-2541f34b24f7.png)
- 특정 투표 컨텐츠에 댓글을 볼 수 있는 댓글 리스트 UI 를 확인할 수있다.

## 📝 Todo
- [x] 댓글의 mock data 형태 만들기
- [x] 유저 정보 및 댓글, 좋아요 렌더링하기
- [x] 최신순, 좋아요 순으로 렌더링하기
- [x] 좋아요 클릭 기능 구현
- [x] 댓글 없을때 UI 구현

## ‼️ 주의 사항
- 우선 api 연동은 하지 않고 순수 react 로 연동할까? 아니면 바로 mock 서버로 만들어서 렌더링할까?? 고민중.. (현우님과 논의해보기?)
