### ISSUE TITLE
[feat] 메인페이지 캐러셀 구현

### ISSUE THREAD

**Issue by hwookim** [YAPP-Github/21st-Web-Team-2-FE#48]
## 💡 목적

![image](https://user-images.githubusercontent.com/45786387/211855747-5332f1c5-e5ad-4823-9a5e-2303ec9471c9.png)

## 📝 Todo

- [x] 좌우 이동 가능한 캐러셀 구현
- [x] 끝 도달 시 버튼 비활성화
- [x] 이동 트랜지션 구현
