### ISSUE TITLE
[feat] api 주소 env파일로 관리

### ISSUE THREAD

**Issue by hwookim** [YAPP-Github/21st-Web-Team-2-FE#59]
## 💡 목적

- env 파일로 관리해서 하드코딩 요소를 제거

## 📝 Todo

- [x] env파일로 관리되는 구조 구현
- [x] env.sample 추가
- [x] chromatic에서 읽어들일 수 있도록 github secrets 추가
